### ISSUE TITLE
Kommunikation: Arduino - Raspberrie

### ISSUE THREAD

**Issue by RomanGsch** [RomanGsch/Praxisprojekt---Mama-Lauda#15]
Verbindung zwischen Arduino und Raspberrie Pi herstellen.
* Start / Stopp Funktion

**Comment by mikefoelsner** [comment]
@elnoscho Master (RaspB) <---> Slave (Arduino)

**Comment by elnoscho** [comment]
wurde heute probiert und ins arduino programm geladen, start funktioniert, stop noch nicht. 
https://github.com/RomanGsch/Praxisprojekt---Mama-Lauda/blob/master/Arduino/Motorsteuerung_15012020/Motorsteuerung_15012020_mit_RaspPiGPIO.ino

**Comment by elnoscho** [comment]
eventueller fehler: benötigt auch einen levelshifter zwischen arduino(5v) und rpi (3v3)!! müsste dann einwandfrei funktionieren

**Comment by elnoscho** [comment]
start und stop läuft einwandfrei, probleme waren wegen erstens 3v3 und 5v zwischen den beiden und dass nach der if kein else mit bremsen() im arduino war
