### ISSUE TITLE
Kommunikation: Basisstation - Raspberrie Pi

### ISSUE THREAD

**Issue by RomanGsch** [RomanGsch/Praxisprojekt---Mama-Lauda#16]
Herstellen einer Verbindung zwischen der Basisstation (PC) und dem Raspberrie Pi
* VCN auf Raspberrie

**Comment by elnoscho** [comment]
wurde bereits getestet und funktioniert einwandfrei:
mit 10.1.1.150/24 kann pi über LAN gefunden werden. über LEANLAB kann bereits eine Verbidnugn zum Raspberry während der fahrt bekommen werden

**Comment by elnoscho** [comment]
läuft wie gehbat, gui startet ah automatisch, cam laft ah. yeah
