### ISSUE TITLE
Temperatursensor Ansteuerung: Safety Function

### ISSUE THREAD

**Issue by RomanGsch** [RomanGsch/Praxisprojekt---Mama-Lauda#17]
Ansteuerung des Temperatursensores zur Safety Function
* Stopp bei Temp. Grenze
* Rückwärts bei zu hoher Temp.

**Comment by mikefoelsner** [comment]
Habe den Kombisensor (Temp-Humidity) mit Arduino getestet. [Type: KY-015]
[Adafruit_DHT library + Programm]

Funktioniert, jedoch liefert der Sensor (laut Datenblatt) maximal alle 2sec ein neues Signal.
@elnoscho Wie schauen deine Sensoren aus?

**Comment by mikefoelsner** [comment]
Code für Temperaturlanze DS18B20 + Bibliotheken sind auf GitHub hochgeladen.
Next Steps: Sensor Verkabelung, Upload des Codes, Testing

Achtung: Bei der Verkabelung ! (siehe Bild)
![AnschlussSensorLanze](https://user-images.githubusercontent.com/59766204/72893253-e3e27500-3d18-11ea-862f-cf3642a020a2.jpg)

**Comment by elnoscho** [comment]
is jetzt aufn arudino, hab des in de gui eingebaut und läuft!! auch habi an grenzwert vo 30 grad moi eine tu. kun ma donn nu ändern
