### ISSUE TITLE
Temperatursensor: Übergabe an Basisstation

### ISSUE THREAD

**Issue by RomanGsch** [RomanGsch/Praxisprojekt---Mama-Lauda#18]
Übergabe der Temperaturwerte vom Sensor an die Basisstation

**Comment by elnoscho** [comment]
anzeige des temperatursensors in der gui, eventuell noch rauch (mit rauch schaltung)

**Comment by elnoscho** [comment]
DHT11 ausprobiert, läuft und gibt feuchtigkeuit und temperatur zurück. datei: temp

**Comment by elnoscho** [comment]
wurde schon probiert in di GUI einzubauen, probleme mit aktualisierung des aktuellen wert
