### ISSUE TITLE
LED-Ansteuerung und Lüfter

### ISSUE THREAD

**Issue by RomanGsch** [RomanGsch/Praxisprojekt---Mama-Lauda#19]
LED-Ansteuerung programmieren.

**Comment by mikefoelsner** [comment]
Einzel Dokument (Arduino-Programm) - Ansteuerung des LED Bandes bei Bewegung des Autos

**Comment by elnoscho** [comment]
hab die LEDs mit dem Raspberry programmiert, mit PWM und jeweils 3 GPIOs vom RPi. Geht nicht anders.
Weitere schritte: die LEDs miteinander Parallel schalten und mit 3 GPIOs (24-R,23-G,18-B) betreiben. programm ist im Repo.

**Comment by elnoscho** [comment]
wurde jetzt zusammen mit relai und den ausgang vo raspberry verwendet. im hauptprogramm soll dann ein button bzw. ein automatischer start eingebaut werden!!

**Comment by elnoscho** [comment]
kann ma mit der gui schalten und auch mit schwellenwert über den rauchsensor, kann ma aber leicht ausbauen...
