### ISSUE TITLE
Teile für Bericht verfassen: Hardware

### ISSUE THREAD

**Issue by RomanGsch** [RomanGsch/Praxisprojekt---Mama-Lauda#31]
Konzeptionierung Mechanischer Aufbau
Mechanischer Aufbau
Verwendete Sensoren und Aktoren
* Was machen diese?

Bitte kurz beschreiben und im Teamsordner ablegen.

**Comment by ChristophMaurberger** [comment]
Marco hat Bauteilbeschreibung gemacht - zu finden unter Hardware
